#
for sp in FV FL FP KV KL KP VL VP LP;do 
	cd $sp
	mkdir ROC
	for ms in *fvout;do                                                                                                                                    
	    sed -n '1,1001p' $ms > fvec
	    sed -n -e '1p' -e '1001,$p' $ms > ${ms}.2
	    paste ../2L.cols fvec > ROC/${ms}.ROC.fvec
	done
	mv mig12.msout3.fvout.2 mig12.msOut
	mv mig21.msout3.fvout.2 mig21.msOut
	mv noMig.msout3.fvout.2 noMig.msOut
	cd ..
done
#
for sp in FV FL FP KV KL KP VL VP LP;do 
	python ~/programs_that_work/FILET/buildThreeClassTrainingSet.py trainingSims/$sp/ trainingSets/threeClass.${sp}.mask.fvec
done

# python ~/programs_that_work/FILET/classifyChromosome.py classifier/threeClass.${sp}.mask.p featureVectors/slide/X_slide .05 results/${sp}
